---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7
    image: centos/systemd
    privileged: true
    command: /sbin/init
    security_opts:
      - seccomp=unconfigured
    capabilities:
      - SYS_ADMIN
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
